name: CI
on:
  pull_request:

  push:
    branches:
      - master 

jobs:
  docker:
    name: Test Docker build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/bake-action@v6
        with:
          files: Dockerfile
          source: .
